server:
  rootPath: /api/ccmevent
  applicationConnectors:
    - type: http
      port: 7280
    - type: https
      port: 7281
      keyStorePath: keystore.jks
      keyStorePassword: password
  adminConnectors:
    - type: http
      port: 8191
      
connectors:
  - port: 9890
    secure: true
    keyFilePath: key.pem
    certFilePath: cert.pem
  - port: 9889
harness-mongo:
  uri: mongodb://localhost:27017/harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

events-mongo:
  uri: mongodb://localhost:27017/events
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

secretsConfiguration:
  secretResolutionEnabled: false
  gcpSecretManagerProject: ccm-play

eventDataBatchQueryConfig:
  queryBatchSize: 4000
  enableBatchWrite: true
