accountId: D3fzqqYxSmGYPzWMvroIWw
delegateToken: e5379ede3694eefa057bf2b5e13645c5
managerUrl: https://qa.harness.io/gratis/api/
verificationServiceUrl: https://qa.harness.io/gratis/verification/
cvNextGenUrl: https://qa.harness.io/gratis/cv/api/
heartbeatIntervalMs: 60000
localDiskPath: /tmp
doUpgrade: false
pollForTasks: false
description: description here
managerTarget: localhost:9880
managerAuthority: localhost
queueFilePath: ../eventQueue
grpcServiceEnabled: true
grpcServiceConnectorPort: 8080
logStreamingServiceBaseUrl: https://qa.harness.io/gratis/log-service/
clientToolsDownloadDisabled: false
installClientToolsInBackground: true

# Required for local development as manger uses self-signed cert
trustAllCertificates: true
