# Dropwizard config
server:
  allowedMethods: ["GET"]
  adminConnectors: []
  applicationConnectors:
    - type: http
      port: 3460
      maxRequestHeaderSize: 100KiB
  rootPath: /api
  maxThreads: 1024

logging:
  type: external

# Delegate Config
accountId: zEaak-FLS425IEO7OLzMUg
delegateToken: 876c7daa24bc66d4b176b82d7368a442
managerUrl: https://qa.harness.io/api/
verificationServiceUrl: https://qa.harness.io/verification/
cvNextGenUrl: https://qa.harness.io/cv/api/
heartbeatIntervalMs: 60000
localDiskPath: /tmp
doUpgrade: false
pollForTasks: false
description: description here
managerTarget: localhost:9880
managerAuthority: localhost
queueFilePath: ../eventQueue
grpcServiceEnabled: true
grpcServiceConnectorPort: 8080
logStreamingServiceBaseUrl: https://qa.harness.io/log-service/
clientToolsDownloadDisabled: true
installClientToolsInBackground: true

# Required for local development as manger uses self-signed cert
trustAllCertificates: true